#import "main.typ": *

#pedigree(length: 2cm, {
  individual(1, 1, "female", dead: "double", propositus: bottom + right, label: "Alice", dead-style: (paint: green))
  individual(1, 2, "male", fill: "filled", label: "Bob", fill-style: red)
  individual(2, 1, "female", label: none)
  individual(2, 2, "male")
  individual(2, 3, "female", fill: "left", fill-style: red, empty-style: green)
  individual(2, 4, "unknown", fill: "left")
  individual(3, 1, "female", adopted: "alt", propositus: true, propositus-style: (paint: green), adopted-style: (paint: red))
  individual(3, 2, "female", adopted: true, propositus: top, propositus-style: (paint: red), adopted-style: (dash: "dashed"))
  individual(3, 3, "male", fill: "filled")
  individual(3, 4, "male", fill: "unknown", propositus: true, fill-style: red)
  duplicate(3, "i2-3", bezier: 1.25, curve-style: (paint: yellow.darken(40%)), label: [Foobar])
  individual(3, 6, "male", stroke-style: (dash: "dashed"), in-label: [P])
  union("i1-1", "i1-2", consanguineous: true, divorced: 2, style: (dash: "dashed"), divorced-style: (paint: blue), label: [Foo])
  union("i2-1", "i2-2", divorced: true, divorced-style: (paint: purple), style: (paint: orange))
  union("i2-3", "i2-4", label: [Blehj])
  union("i3-2", "i3-3", label: [Union])
  twins("i3-4", "d1", "i3-6", monozygotic: ("unknown", "true"), style: (paint: red), monozygotic-style: (dash: "dashed"))
  children("u1", "i2-2", "i2-3", line-of-descent-style: (paint: purple), sibling-line-style: (paint: blue), child-line-style: ((paint: red), (paint: blue)), label: [Hi])
  children("u2", "i3-1", child-line-style: (dash: "dashed"), line-of-descent-style: (dash: "dashed"))
  children("u3", "i3-2", "i3-3", "t1")
  children("u4", infertile: true, no-children-style: (paint: blue))
})

// #pedigree(length: 1cm, {
//   individual(1, 1, "male")
//   individual(1, 2, "female")
//   individual(1, 3, "male")
//   individual(1, 4, "female")
//   individual(2, 1, "male")
//   duplicate(2, "i2-2")
//   individual(2, 3, "male")
//   individual(2, 4, "female")
//   individual(2, 2, "female")
//   individual(2, 5, "male")
//   individual(2, 6, "female")
//   individual(3, 1, "male", partial-fill)
//   individual(3, 3, "female", partial-fill)
//   individual(3, 4, "male", dead: true)
//   individual(3, 5, "male")
//   individual(3, 6, "male")
//   individual(3, 7, "male", partial-fill)
//   individual(3, 8, "female", partial-fill)
//   individual(3, 9, "female")
//   individual(3, 10, "female")
//   individual(3, 11, "unknown", dead: true)
//   individual(3, 12, "male")
//   individual(4, 1, "male", "filled", propositus: true)
//   individual(4, 2, "male", "filled", propositus: true)

//   union("i1-1", "i1-2")
//   union("i1-3", "i1-4")
//   union("i2-1", "d1")
//   union("i2-3", "i2-4")
//   union("i2-5", "i2-6")
//   union("i3-1", "i3-3", consanguineous: true)
//   union("i3-7", "i3-8", consanguineous: true)

//   children("u1", "i2-1", "i2-3")
//   children("u2", "i2-2", "i2-6")
//   children("u3", "i3-1")
//   children("u4", "i3-3", "i3-4", "i3-5", "i3-6", "i3-7")
//   children("u5", "i3-8", "i3-9", "i3-10", "i3-11", "i3-12")
//   children("u6", "i4-1")
//   children("u7", "i4-2")

// })

// #pedigree({
//   individual(1, 1, "female")
//   individual(1, 2, "male")
//   individual(2, 1, "male")
//   individual(2, 2, "female")
//   individual(2, 3, "male")
//   individual(2, 4, "female")
//   individual(3, 1, "female")
//   individual(3, 2, "female")
//   individual(4, 1, "female")
//   individual(4, 2, "male")
//   individual(5, 1, "female", "filled")

//   union("i1-1", "i1-2")
//   union("i2-1", "i2-2")
//   union("i2-3", "i2-4")
//   union("i4-1", "i4-2", consanguineous: true)

//   children("u1", "i2-2", "i2-3")
//   children("u2", "i3-1")
//   children("u3", "i3-2")
//   children("i3-1", "i4-1")
//   children("i3-2", "i4-2")
//   children("u4", "i5-1")
// })

// #pedigree({
//   individual(1, 1, "male")
//   individual(1, 2, "female")
//   individual(1, 3, "male")
//   individual(1, 4, "female")
//   individual(2, 1, "male")
//   individual(2, 2, "female")
//   individual(3, 1, "female")
//   individual(3, 2, "male")
//   individual(4, 1, "male")
//   individual(4, 2, "female")

//   union("i1-1", "i1-2")
//   union("i1-3", "i1-4")
//   union("i2-1", "i2-2")
//   union("i3-1", "i3-2")
//   union("i4-1", "i4-2", consanguineous: true)

//   children("u1", "i2-1", "i3-1")
//   children("u2", "i2-2", "i3-2")
//   children("u3", "i4-1")
//   children("u4", "i4-2")
// })

// #pedigree(convergence-time: 200, {
//   individual(1, 1, "male")
//   individual(1, 2, "female")
//   individual(2, 1, "female")
//   individual(2, 2, "male")
//   individual(2, 3, "female")
//   individual(2, 4, "male")
//   individual(2, 5, "male")
//   individual(2, 6, "female")
//   individual(3, 1, "male")
//   individual(3, 2, "female")
//   individual(3, 3, "male")
//   individual(3, 4, "female")
//   individual(3, 5, "male")
//   individual(3, 6, "female")
//   individual(4, 1, "male")
//   individual(4, 2, "female")
//   individual(4, 3, "male")
//   individual(4, 4, "female")
//   individual(4, 5, "female")
//   individual(4, 6, "male")
//   individual(4, 7, "female")
//   individual(4, 8, "male")
//   individual(4, 9, "female")
//   individual(4, 10, "male")
//   individual(5, 1, "unknown")
//   individual(5, 2, "unknown")
//   individual(5, 3, "unknown")
//   individual(5, 4, "female", "filled")
//   individual(5, 5, "male", "filled")
//   individual(5, 6, "female")
//   individual(5, 7, "female", "filled")
//   individual(5, 8, "female", "filled")
//   individual(5, 9, "female")
//   individual(5, 10, "female")
//   individual(5, 11, "female")
//   individual(5, 12, "female", "filled")
//   individual(5, 13, "female")

//   union("i1-1", "i1-2")
//   union("i2-1", "i2-2")
//   union("i2-3", "i2-4")
//   union("i2-5", "i2-6")
//   union("i3-1", "i3-2")
//   union("i3-3", "i3-4")
//   union("i3-5", "i3-6")
//   union("i4-3", "i4-4", consanguineous: true)
//   union("i4-5", "i4-6", consanguineous: true)
//   union("i4-8", "i4-9", consanguineous: true)

//   children("u1", "i2-4", "i2-5")
//   children("u2", "i3-2", "i3-3")
//   children("u3", "i3-4", "i3-6")
//   children("u4", "i4-8")
//   children("u5", "i4-1", "i4-2", "i4-3")
//   children("u6", "i4-4", "i4-5", "i4-7", "i4-9", "i4-10")
//   children("u7", "i4-6")
//   children("u8", "i5-1", "i5-2", "i5-3", "i5-4", "i5-5", "i5-6", "i5-7")
//   children("u9", "i5-8", "i5-9", "i5-10")
//   children("u10", "i5-11", "i5-12", "i5-13")
// })

// #pedigree({
//   individual(1, 1, "male")
//   individual(1, 2, "female")
//   individual(2, 1, "male")
//   individual(3, 1, "female")

//   union("i1-1", "i1-2")
//   children("u1", "i2-1", "i3-1")
// })

// #pedigree({
//   individual(1, 1, "male")
//   individual(1, 2, "female")
//   individual(2, 1, "male")
//   individual(2, 2, "female")
//   individual(2, 3, "male")
//   individual(2, 4, "male")
//   individual(2, 5, "male")
//   individual(2, 6, "male")

//   union("i1-1", "i1-2")
//   // union("i2-1", "i2-2")
//   children("u1", "i2-6")
// })

// #pedigree(length: 2cm, {
//   individual(1, 1, "male", "empty", fill-color: red)
//   individual(1, 2, "female", "empty", fill-color: red)
//   individual(1, 3, "unknown", "empty", fill-color: red)
//   individual(1, 4, "miscarriage", "empty", fill-color: red)

//   individual(2, 1, "male", "filled", fill-color: red)
//   individual(2, 2, "female", "filled", fill-color: red)
//   individual(2, 3, "unknown", "filled", fill-color: red)
//   individual(2, 4, "miscarriage", "filled", fill-color: red)

//   individual(3, 1, "male", "unknown", fill-color: red)
//   individual(3, 2, "female", "unknown", fill-color: red)
//   individual(3, 3, "unknown", "unknown", fill-color: red)
//   individual(3, 4, "miscarriage", "unknown", fill-color: red)

//   individual(4, 1, "male", "I", fill-color: red)
//   individual(4, 2, "female", "I", fill-color: red)
//   individual(4, 3, "unknown", "I", fill-color: red)
//   individual(4, 4, "miscarriage", "I", fill-color: red)

//   individual(5, 1, "male", "II", fill-color: red)
//   individual(5, 2, "female", "II", fill-color: red)
//   individual(5, 3, "unknown", "II", fill-color: red)
//   individual(5, 4, "miscarriage", "II", fill-color: red)

//   individual(6, 1, "male", "III", fill-color: red)
//   individual(6, 2, "female", "III", fill-color: red)
//   individual(6, 3, "unknown", "III", fill-color: red)
//   individual(6, 4, "miscarriage", "III", fill-color: red)

//   individual(7, 1, "male", "IV", fill-color: red)
//   individual(7, 2, "female", "IV", fill-color: red)
//   individual(7, 3, "unknown", "IV", fill-color: red)
//   individual(7, 4, "miscarriage", "IV", fill-color: red)

//   individual(8, 1, "male", "dot", fill-color: red)
//   individual(8, 2, "female", "dot", fill-color: red)
//   individual(8, 3, "unknown", "dot", fill-color: red)
//   individual(8, 4, "miscarriage", "dot", fill-color: red)
// })

// #set page(height: auto, width: 50cm)
// #pedigree(convergence-time: 400, length: 0.75cm, {
//   individual(1, 1, "female", "left", label: [Victoria])
//   individual(1, 2, "male", label: [Albert])

//   individual(2, 1, "female", label: [Victoria])
//   individual(2, 2, "male", label: none)
//   individual(2, 3, "female", "left", label: [Alice])
//   individual(2, 4, "male", label: [Louis $"IV"$])
//   individual(2, 5, "male", label: none)
//   individual(2, 6, "male", label: none)
//   individual(2, 7, "female", label: none)
//   individual(2, 8, "male", label: [Edward $"VII"$])
//   individual(2, 9, "female", label: [Alexandra])
//   individual(2, 10, "female", label: none)
//   individual(2, 11, "male", "filled", label: [Leopold])
//   individual(2, 12, "female", "left", label: [Beatrice])
//   individual(2, 13, "male", label: none)
//   individual(2, 14, "female", label: [Helena])

//   individual(3, 1, "male", label: none)
//   individual(3, 2, "male", label: none)
//   individual(3, 3, "female", "left", label: [Irene])
//   individual(3, 4, "male", "filled", label: none)
//   individual(3, 5, "female", "left", label: [Alexandra\ Nicholas $"II"$])
//   individual(3, 6, "male", label: none)
//   individual(3, 7, "female", label: none)
//   individual(3, 8, "female", label: none)
//   individual(3, 9, "male", label: none)
//   individual(3, 10, "female", "unknown", label: none)
//   individual(3, 11, "male", label: none)
//   individual(3, 12, "male", label: [George $"V"$])
//   individual(3, 13, "female", label: [Mary])
//   individual(3, 14, "female", "left", label: none)
//   individual(3, 15, "male", label: none)
//   individual(3, 16, "male", label: none)
//   individual(3, 17, "male", label: none)
//   individual(3, 18, "female", "left", label: [Victoria])
//   individual(3, 19, "male", label: [Alfonso $"XIII"$])
//   individual(3, 20, "male", "filled", label: none)
//   individual(3, 21, "male", "filled", label: none)

//   individual(4, 1, "male", label: none)
//   individual(4, 2, "male", "filled", label: none)
//   individual(4, 3, "male", "filled", label: none)
//   individual(4, 4, "female", "unknown", label: [Olga])
//   individual(4, 5, "female", "unknown", label: [Tatiana])
//   individual(4, 6, "female", "unknown", label: [Marie])
//   individual(4, 7, "female", "unknown", label: [Anastasia])
//   individual(4, 8, "male", "filled", label: [Alexei])
//   individual(4, 9, "female", "unknown", label: none)
//   individual(4, 10, "male", label: none)
//   individual(4, 11, "male", "filled", label: none)
//   individual(4, 12, "female", "unknown", label: none)
//   individual(4, 13, "male", label: none)
//   individual(4, 14, "male", "filled", label: none)
//   individual(4, 15, "male", "filled", label: none)
//   individual(4, 16, "male", label: [Juan])
//   individual(4, 17, "female", "unknown", label: none)

//   individual(5, 1, "male", label: none)
//   individual(5, 2, "male", label: none)
//   individual(5, 3, "female", label: none)
//   individual(5, 4, "male", label: none)
//   individual(5, 5, "female", "unknown", label: none)
//   individual(5, 6, "male", label: [George $"VI"$])
//   individual(5, 7, "female", label: none)
//   individual(5, 8, "male", label: none)
//   individual(5, 9, "female", "unknown", label: none)
//   individual(5, 10, "female", "unknown", label: none)
//   individual(5, 11, "male", label: none)
//   individual(5, 12, "male", label: [Juan Carlos])

//   individual(6, 1, "male", label: [Philip])
//   individual(6, 2, "female", label: [Elizabeth $"II"$])
//   individual(6, 3, "female", label: [Margaret])

//   individual(7, 1, "female", label: [Diana])
//   individual(7, 2, "male", label: [Charles])
//   individual(7, 3, "male", label: [Andrew])
//   individual(7, 4, "female", label: [Sarah])
//   individual(7, 5, "male", label: [Edward])
//   individual(7, 6, "female", label: [Anne])

//   individual(8, 1, "male", label: [William])
//   individual(8, 2, "male", label: [Harry])

//   union("i1-1", "i1-2")

//   union("i2-1", "i2-2")
//   union("i2-3", "i2-4")
//   union("i2-8", "i2-9")
//   union("i2-10", "i2-11")
//   union("i2-12", "i2-13")

//   union("i3-2", "i3-3", consanguineous: true)
//   union("i3-5", "i3-6")
//   union("i3-10", "i3-11")
//   union("i3-12", "i3-13")
//   union("i3-14", "i3-15")
//   union("i3-18", "i3-19")
//   union("i4-9", "i4-10")

//   union("i5-4", "i5-5")
//   union("i5-6", "i5-7")

//   union("i6-1", "i6-2", consanguineous: true)

//   union("i7-1", "i7-2")
//   union("i7-3", "i7-4")

//   children("u1", "i2-1", "i2-3", "i2-5", "i2-6", "i2-7", "i2-8", "i2-11", "i2-12", "i2-14")
//   children("u2", "i3-1", "i3-2")
//   children("u3", "i3-3", "i3-4", "i3-5", "i3-7", "i3-8", "i3-9", "i3-10")
//   children("u4", "i3-12")
//   children("u5", "i3-14", "i3-16", "i3-17")
//   children("u6", "i3-18", "i3-20", "i3-21")
//   children("u7", "i4-1", "i4-2", "i4-3")
//   children("u8", "i4-4", "i4-5", "i4-6", "i4-7", "i4-8")
//   children("u9", "i5-1", "i5-2", "i5-3", "i5-5")
//   children("u10", "i5-6", "i5-8")
//   children("u11", "i4-9", "i4-11")
//   children("u12", "i4-12", "i4-13", "i4-14", "i4-15", "i4-16", "i4-17")
//   children("u13", "i5-9", "i5-10", "i5-11")
//   children("i4-16", "i5-12")
//   children("u14", "i6-1")
//   children("u15", "i6-2", "i6-3")
//   children("u16", "i7-2", "i7-3", "i7-5", "i7-6")
//   children("u17", "i8-1", "i8-2")
// })

// #pedigree(length: 2cm, {
//   individual(1, 1, "male", dead: true)
//   individual(1, 2, "female", dead: true, label: [Alice Murray\ d. age $52$])
//   individual(2, 1, "male", label: [Robert Jones\ b. $22$.$01$.$1935$])
//   individual(2, 2, "female", "filled", dead: true, label: [Mollie Jones\ b. $14$.$06$.$1937$\ diag. age $35$\ d. age $40$])
//   individual(2, 3, "male", dead: true, label: [Michael Murray\ b. $28$.$06$.$1935$\ d. age $67$])
//   individual(2, 4, "female", label: [Joan Murray])
//   individual(2, 5, "male", label: [Peter Murray\ b. $05$.$11$.$1936$])
//   individual(3, 1, "male", label: [John Smith\ b. $26$.$04$.$1961$])
//   individual(3, 2, "female", "filled", propositus: true, label: [Julie Smith\ b. $30$.$03$.$1961$\ diag. age $44$])
//   individual(3, 3, "female", label: [Margaret Jones\ b. $12$.$02$.$1968$])
//   individual(3, 4, "female", "filled", dead: true, label: [Mary Murray\ b. $15$.$11$.$1964$\ diag. age $40$\ d. age $42$])
//   individual(3, 5, "female", label: [Sarah Murray\ b. $04$.$12$.$1966$])
//   individual(4, 1, "female", label: [Melanie Smith\ b. $19$.$08$.$1990$])
//   individual(4, 2, "female", label: [Charlotte Smith\ b. $06$.$11$.$1992$])
//   individual(4, 3, "female", label: [Gemma Smith\ b. $09$.$05$.$1994$])

//   union("i1-1", "i1-2")
//   union("i2-1", "i2-2")
//   union("i2-3", "i2-4")
//   union("i3-1", "i3-2")

//   children("u1", "i2-2", "i2-3", "i2-5")
//   children("u2", "i3-2", "i3-3")
//   children("u3", "i3-4", "i3-5")
//   children("u4", "i4-1", "i4-2", "i4-3")
// })

#pedigree(length: 2cm, convergence-time: 250, empty-style: red, {
  individual(1, 1, "male")
  individual(1, 2, "female")
  individual(2, 1, "female")
  individual(2, 2, "male")
  individual(2, 3, "female")
  individual(2, 4, "male")
  individual(3, 1, "male")
  individual(3, 2, "female")
  individual(3, 3, "male")
  individual(3, 4, "male")
  individual(3, 5, "female")
  individual(3, 6, "female")
  individual(4, 1, "female")
  individual(4, 2, "female")
  individual(5, 1, "male")
  individual(6, 1, "male")
  individual(6, 2, "male")
  individual(6, 3, "male")
  individual(6, 4, "male", fill: "filled", propositus: true)

  union("i1-1", "i1-2")
  union("i2-1", "i2-2")
  union("i2-3", "i2-4")
  union("i3-1", "i4-1", consanguineous: true, label: [Evil])
  union("i3-2", "i3-3")
  union("i3-4", "i3-5")
  union("i5-1", "i4-2", consanguineous: true, label: [Wowee])

  children("u1", "i2-2", "i2-4")
  children("u2", "i3-1")
  children("u3", "i3-3", "i3-4", "i3-6")
  children("u4", "i5-1")
  children("u5", "i4-1")
  children("u6", "i4-2")
  children("u7", "i6-1", "i6-2", "i6-3", "i6-4")
})

#pedigree(length: 2cm, generation-labels: false, {
  duplicate(1, "i3-2", bezier: -1.5)
  individual(1, 2, "female", label: [Widow])
  individual(1, 3, "male", label: none)
  individual(2, 1, "male", label: [Baby])
  individual(2, 2, "female", label: [Daughter])
  individual(2, 3, "male", label: [Dad])
  individual(2, 4, "female", label: [Mom])
  individual(3, 1, "male", label: [Son])
  individual(3, 2, "male", label: [Me])

  union("d1", "i1-2")
  union("i1-2", "i1-3")
  union("i2-2", "i2-3")
  union("i2-3", "i2-4")

  children("u1", "i2-1")
  children("u2", "i2-2")
  children("u3", "i3-1")
  children("u4", "i3-2")
})
